### ISSUE TITLE
error coming while running npm start

### ISSUE THREAD

**Issue by Shivendra12131** [shashiben/Hostel-Management#5]
Starting the development server...

/Users/shivendra/Desktop/new_project/Hostel-Management/frontend/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/shivendra/Desktop/new_project/Hostel-Management/frontend/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/shivendra/Desktop/new_project/Hostel-Management/frontend/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/shivendra/Desktop/new_project/Hostel-Management/frontend/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/shivendra/Desktop/new_project/Hostel-Management/frontend/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/shivendra/Desktop/new_project/Hostel-Management/frontend/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/shivendra/Desktop/new_project/Hostel-Management/frontend/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/shivendra/Desktop/new_project/Hostel-Management/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/shivendra/Desktop/new_project/Hostel-Management/frontend/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v21.1.0
shivendra@Shivendras-MacBook-Air frontend % node server.js
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '/Users/shivendra/Desktop/new_project/Hostel-Management/frontend/server.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v21.1.0

**Comment by Abhigna-D** [comment]
go to your package.json and change "start": "react-scripts start" to "start": "react-scripts --openssl-legacy-provider start"

**Comment by anasaijaz** [comment]
Looks like some dependencies are still legacy?

**Comment by crysosancher** [comment]
npm run start                 

> hostel-app@0.1.0 start
> react-scripts --openssl-legacy-provider start

node:internal/modules/cjs/loader:596
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /home/cryso/Documents/Projects/mamaji/Hostel-Management/frontend/node_modules/postcss-safe-parser/node_modules/postcss/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:303:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:650:9)
    at resolveExports (node:internal/modules/cjs/loader:589:36)
    at Module._findPath (node:internal/modules/cjs/loader:666:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1128:27)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/cryso/Documents/Projects/mamaji/Hostel-Management/frontend/node_modules/postcss-safe-parser/lib/safe-parser.js:1:17)
    at Module._compile (node:internal/modules/cjs/loader:1368:14) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v21.7.1
